server:
  port: 8888
  context-path: /web

spring:
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1000
    minIdle: 500
    maxActive: 20000
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

    #redis
  #redis:
   # host: 192.168.239.128
   # password: 123456
    #port: 6379
    ##timeout: 10000
   # pool:
     # max-active: 100
     # max-wait: -1
     # max-idle: 5
     # min-idle: 0

#rabbitMQ
  rabbitmq:
    host: 192.168.239.130
    port: 5672
    username: demo
    password: demo
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        auto-startup: true
        prefetch: 1
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

redis:
  host: 192.168.239.128
  port: 6379
  timeout: 3
  password: 123456
  poolMaxTotal: 10000
  poolMaxIdle: 100
  poolMaxWait: 300




mybatis:
  config-location: classpath:SqlMapper.xml
  mapper-locations:  classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




